// <auto-generated />
namespace AkureTraining.Core.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class Added_accountAnd_messages_class : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Added_accountAnd_messages_class));
        
        string IMigrationMetadata.Id
        {
            get { return "201708030858235_Added_accountAnd_messages_class"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
